### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by sagikazarmark** [thephpleague/tactician-command-events#2]
@rosstuck Do you think that the `handle` keyword still overlaps with something in the new architecture? If yes, I will rename the methods to `stopException` and `isExceptionStopped`.

**Comment by rosstuck** [comment]
Yeah, as discussed I think we should use `handle` only in the context of the Command Handlers to prevent confusion.

`isExceptionStopped` reads a little off to me... Just throwing some alternatives out there, do any of them ring true with you?
- suppressException / isExceptionSuppressed (personal fave)
- hideException / isExceptionHidden (hide kinda captures the intent)
- stopExceptionBubbling / isBubblingStopped (ala jquery)

**Comment by sagikazarmark** [comment]
My problem with all of them is that they suggest that the exception is not properly handled, but "suppressed" some way.

**Comment by rosstuck** [comment]
We _are_ suppressing the event from raising/bubbling which is the default behavior. True, the intent ought to be that we're shuffling it off to some other mechanism for handling but that's not with this method does, it's only for the suppression, not the handling.

We could try to focus on the opposite here raiseException / stopExceptionFromBeingRaised / shouldExceptionBeRaised. It reads really funny though.

**Comment by sagikazarmark** [comment]
Hm, catchException/isExceptionCatched?

**Comment by rosstuck** [comment]
Would need to be `isExceptionCaught` or `shouldCatchException` because English is weird. But I like that better. :)

**Comment by sagikazarmark** [comment]
So `catchException` and `isExceptionCaught` then?

**Comment by rosstuck** [comment]
Works for me! :grinning:
